<?php

namespace Database\Seeders;

use App\Models\Article;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ArticleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $articles = [
            [
                'id' => 1,
                'name' => 'LEGO City Policía Aérea',
                'brand_id' => 1,
                'category_id' => 1,
                'description' => 'Set de construcción con helicóptero y moto para patrullar la ciudad.',
                'min_age' => 6,
                'max_age' => 12,
                'price' => 34.99,
                'image' => '1.webp',
            ],
            [
                'id' => 2,
                'name' => 'LEGO Star Wars: Caza X-Wing',
                'brand_id' => 1,
                'category_id' => 1,
                'description' => 'Caza estelar clásico de la saga Star Wars, con minifiguras de Luke y R2-D2.',
                'min_age' => 8,
                'max_age' => 14,
                'price' => 79.99,
                'image' => '2.webp',
            ],
            [
                'id' => 3,
                'name' => 'Playmobil Casa Moderna',
                'brand_id' => 2,
                'category_id' => 1,
                'description' => 'Casa de muñecas Playmobil con figuras y accesorios.',
                'min_age' => 4,
                'max_age' => 10,
                'price' => 59.99,
                'image' => '3.jpg',
            ],
            [
                'id' => 4,
                'name' => 'Barbie Dreamhouse',
                'brand_id' => 3,
                'category_id' => 2,
                'description' => 'La icónica casa de Barbie con tres pisos, ascensor y piscina.',
                'min_age' => 6,
                'max_age' => 12,
                'price' => 129.99,
                'image' => '4.avif',
            ],
            [
                'id' => 5,
                'name' => 'Hot Wheels Mega Garage',
                'brand_id' => 4,
                'category_id' => 3,
                'description' => 'Garaje con múltiples niveles y rampas para coches Hot Wheels.',
                'min_age' => 5,
                'max_age' => 12,
                'price' => 54.99,
                'image' => '5.avif',
            ],
            [
                'id' => 6,
                'name' => 'Monopoly Classic',
                'brand_id' => 5,
                'category_id' => 4,
                'description' => 'El clásico juego de mesa de compra y venta de propiedades.',
                'min_age' => 8,
                'max_age' => 99,
                'price' => 29.99,
                'image' => '6.jpg',
            ],
            [
                'id' => 7,
                'name' => 'Trivial Pursuit Familia',
                'brand_id' => 5,
                'category_id' => 4,
                'description' => 'Versión familiar del clásico juego de preguntas y respuestas.',
                'min_age' => 8,
                'max_age' => 99,
                'price' => 39.99,
                'image' => '7.jpg',
            ],
            [
                'id' => 8,
                'name' => 'Peluche Pikachu',
                'brand_id' => 6,
                'category_id' => 6,
                'description' => 'Peluche suave de Pikachu, el famoso Pokémon eléctrico.',
                'min_age' => 3,
                'max_age' => 99,
                'price' => 19.99,
                'image' => '8.png',
            ],
            [
                'id' => 9,
                'name' => 'VTech Kidizoom Cámara',
                'brand_id' => 7,
                'category_id' => 8,
                'description' => 'Cámara digital infantil resistente con juegos integrados.',
                'min_age' => 5,
                'max_age' => 10,
                'price' => 49.99,
                'image' => '9.jpg',
            ],
            [
                'id' => 10,
                'name' => 'Fisher-Price Perrito Aprende Conmigo',
                'brand_id' => 8,
                'category_id' => 5,
                'description' => 'Juguete educativo interactivo que enseña letras y canciones.',
                'min_age' => 1,
                'max_age' => 4,
                'price' => 34.99,
                'image' => '10.avif',
            ],
            [
                'id' => 11,
                'name' => 'Ravensburger Puzzle 3D Torre Eiffel',
                'brand_id' => 9,
                'category_id' => 1,
                'description' => 'Puzzle 3D con 216 piezas para construir la Torre Eiffel.',
                'min_age' => 10,
                'max_age' => 99,
                'price' => 32.99,
                'image' => '11.jpg',
            ],
            [
                'id' => 12,
                'name' => 'NERF Elite 2.0 Blaster',
                'brand_id' => 10,
                'category_id' => 7,
                'description' => 'Lanzador de dardos de espuma con alcance de hasta 27 metros.',
                'min_age' => 8,
                'max_age' => 16,
                'price' => 44.99,
                'image' => '12.jpg',
            ],
            [
                'id' => 13,
                'name' => 'Nintendo Switch Lite',
                'brand_id' => 11,
                'category_id' => 8,
                'description' => 'Consola portátil ligera de Nintendo, ideal para jugar en cualquier parte.',
                'min_age' => 7,
                'max_age' => 99,
                'price' => 219.99,
                'image' => '13.avif',
            ],
            [
                'id' => 14,
                'name' => 'LEGO Technic Bugatti Chiron',
                'brand_id' => 1,
                'category_id' => 1,
                'description' => 'Set avanzado para construir una réplica detallada del Bugatti Chiron.',
                'min_age' => 12,
                'max_age' => 99,
                'price' => 349.99,
                'image' => '14.webp',
            ],
            [
                'id' => 15,
                'name' => 'Barbie Doctora',
                'brand_id' => 3,
                'category_id' => 2,
                'description' => 'Muñeca Barbie con bata de doctora y accesorios médicos.',
                'min_age' => 4,
                'max_age' => 10,
                'price' => 17.99,
                'image' => '15.jpg',
            ],
            [
                'id' => 16,
                'name' => 'Hot Wheels Pista Looping Infernal',
                'brand_id' => 4,
                'category_id' => 3,
                'description' => 'Pista de coches con looping y lanzador de alta velocidad.',
                'min_age' => 5,
                'max_age' => 12,
                'price' => 39.99,
                'image' => '16.jpg',
            ],
            [
                'id' => 17,
                'name' => 'LEGO Friends Café del Corazón',
                'brand_id' => 1,
                'category_id' => 1,
                'description' => 'Cafetería colorida con figuras y accesorios para jugar en grupo.',
                'min_age' => 6,
                'max_age' => 12,
                'price' => 39.99,
                'image' => '17.webp',
            ],
            [
                'id' => 18,
                'name' => 'Playmobil Barco Pirata',
                'brand_id' => 2,
                'category_id' => 1,
                'description' => 'Emblemático barco pirata con cañones y tripulación.',
                'min_age' => 5,
                'max_age' => 12,
                'price' => 74.99,
                'image' => '18.jpg',
            ],
            [
                'id' => 19,
                'name' => 'Peluche Stitch 30cm',
                'brand_id' => 6,
                'category_id' => 6,
                'description' => 'Peluche del personaje Stitch, de Disney.',
                'min_age' => 3,
                'max_age' => 99,
                'price' => 24.99,
                'image' => '19.jpg',
            ],
            [
                'id' => 20,
                'name' => 'Hasbro Twister',
                'brand_id' => 5,
                'category_id' => 4,
                'description' => 'Juego físico para moverse sobre un tapete lleno de colores.',
                'min_age' => 6,
                'max_age' => 99,
                'price' => 26.99,
                'image' => '20.jpg',
            ],
            [
                'id' => 21,
                'name' => 'LEGO Harry Potter Hogwarts Express',
                'brand_id' => 1,
                'category_id' => 1,
                'description' => 'Réplica del tren de Hogwarts con figuras y accesorios.',
                'min_age' => 8,
                'max_age' => 14,
                'price' => 99.99,
                'image' => '21.webp',
            ],
            [
                'id' => 22,
                'name' => 'VTech Baby Móvil Proyector',
                'brand_id' => 7,
                'category_id' => 5,
                'description' => 'Móvil musical para cuna con luces y sonidos relajantes.',
                'min_age' => 0,
                'max_age' => 3,
                'price' => 44.99,
                'image' => '22.jpg',
            ],
            [
                'id' => 23,
                'name' => 'NERF Super Soaker Hydro Frenzy',
                'brand_id' => 10,
                'category_id' => 7,
                'description' => 'Pistola de agua a presión con doble chorro.',
                'min_age' => 6,
                'max_age' => 16,
                'price' => 29.99,
                'image' => '23.webp',
            ],
            [
                'id' => 24,
                'name' => 'Fisher-Price Centro de Actividades',
                'brand_id' => 8,
                'category_id' => 5,
                'description' => 'Centro de juegos para bebés con sonidos, luces y piezas móviles.',
                'min_age' => 0,
                'max_age' => 3,
                'price' => 59.99,
                'image' => '24.jpg',
            ],
            [
                'id' => 25,
                'name' => 'Ravensburger Laberinto Mágico',
                'brand_id' => 9,
                'category_id' => 4,
                'description' => 'Juego de mesa de estrategia con laberintos cambiantes.',
                'min_age' => 7,
                'max_age' => 99,
                'price' => 27.99,
                'image' => '25.jpg',
            ],
        ];

        foreach ($articles as $article) {
            $article['stock'] = rand(0, 50);

            Article::create($article);
        }
    }
}
